// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuKiSoBackEnd.Data;

#nullable disable

namespace RuKiSoBackEnd.Migrations
{
    [DbContext(typeof(RuKiSoDataContext))]
    partial class RuKiSoDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.BatchIngredient", b =>
                {
                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BatchId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("BatchIngredients");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            IngredientId = 3,
                            Quantity = 50
                        },
                        new
                        {
                            BatchId = 1,
                            IngredientId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            BatchId = 2,
                            IngredientId = 2,
                            Quantity = 45
                        },
                        new
                        {
                            BatchId = 2,
                            IngredientId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            BatchId = 3,
                            IngredientId = 1,
                            Quantity = 40
                        },
                        new
                        {
                            BatchId = 3,
                            IngredientId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            BatchId = 4,
                            IngredientId = 4,
                            Quantity = 30
                        },
                        new
                        {
                            BatchId = 4,
                            IngredientId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            BatchId = 5,
                            IngredientId = 4,
                            Quantity = 25
                        },
                        new
                        {
                            BatchId = 5,
                            IngredientId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            BatchId = 6,
                            IngredientId = 4,
                            Quantity = 20
                        },
                        new
                        {
                            BatchId = 6,
                            IngredientId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            BatchId = 7,
                            IngredientId = 2,
                            Quantity = 35
                        },
                        new
                        {
                            BatchId = 7,
                            IngredientId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            BatchId = 8,
                            IngredientId = 3,
                            Quantity = 40
                        },
                        new
                        {
                            BatchId = 8,
                            IngredientId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            BatchId = 8,
                            IngredientId = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Batches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EstimateEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Yield")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstimateEndDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        },
                        new
                        {
                            Id = 2,
                            EstimateEndDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            StartDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        },
                        new
                        {
                            Id = 3,
                            EstimateEndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        },
                        new
                        {
                            Id = 4,
                            EstimateEndDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            StartDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        },
                        new
                        {
                            Id = 5,
                            EstimateEndDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        },
                        new
                        {
                            Id = 6,
                            EstimateEndDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            StartDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        },
                        new
                        {
                            Id = 7,
                            EstimateEndDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            StartDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        },
                        new
                        {
                            Id = 8,
                            EstimateEndDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            StartDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Yield = 0
                        });
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gạo nếp",
                            PurchasePrice = 20000.0,
                            Quantity = 300,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nếp cái hoa vàng",
                            PurchasePrice = 25000.0,
                            Quantity = 500,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nếp đen",
                            PurchasePrice = 23000.0,
                            Quantity = 1000,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đòng đòng",
                            PurchasePrice = 30000.0,
                            Quantity = 50,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Men thuốc bắc",
                            PurchasePrice = 150000.0,
                            Quantity = 3,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Men thường",
                            PurchasePrice = 80000.0,
                            Quantity = 1,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Men lá",
                            PurchasePrice = 100000.0,
                            Quantity = 2,
                            Unit = "Kg"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Táo mèo",
                            PurchasePrice = 30000.0,
                            Quantity = 10,
                            Unit = "Kg"
                        });
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nếp đen, men thuốc bắc",
                            Name = "Rượu trắng 45",
                            Price = 50000.0,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nếp cái hoa vàng, men thường",
                            Name = "Rượu trắng 40",
                            Price = 45000.0,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gạo nếp, men lá",
                            Name = "Rượu trắng 35",
                            Price = 40000.0,
                            Quantity = 250
                        },
                        new
                        {
                            Id = 4,
                            Description = "Đòng đòng, men thuốc bắc",
                            Name = "Đòng đòng 45",
                            Price = 75000.0,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 5,
                            Description = "Đòng đòng, men thường",
                            Name = "Đòng đòng 40",
                            Price = 70000.0,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 6,
                            Description = "Đòng đòng, men lá",
                            Name = "Đòng đòng 35",
                            Price = 60000.0,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nếp cái hoa vàng, men lá",
                            Name = "Rượu bách nhật",
                            Price = 40000.0,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 8,
                            Description = "Nếp đen, táo mèo, men thuốc bắc",
                            Name = "Rượu táo mèo",
                            Price = 60000.0,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TranDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TranType")
                        .HasColumnType("bit");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ProductId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 3,
                            Name = "Mua nếp đen",
                            Quantity = 200,
                            TranDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 4600000.0
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 5,
                            Name = "Mua men thuốc bắc",
                            Quantity = 2,
                            TranDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 300000.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bán rượu trắng 45",
                            ProductId = 1,
                            Quantity = 100,
                            TranDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 5000000.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bán đòng đòng 45",
                            ProductId = 4,
                            Quantity = 30,
                            TranDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 2250000.0
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 2,
                            Name = "Mua nếp cái hoa vàng",
                            Quantity = 150,
                            TranDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 3750000.0
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 4,
                            Name = "Mua đòng đòng",
                            Quantity = 50,
                            TranDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 1500000.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bán rượu trắng 40",
                            ProductId = 2,
                            Quantity = 120,
                            TranDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 5400000.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bán đòng đòng 40",
                            ProductId = 5,
                            Quantity = 40,
                            TranDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 2800000.0
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 1,
                            Name = "Mua gạo nếp",
                            Quantity = 180,
                            TranDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 3600000.0
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 7,
                            Name = "Mua men lá",
                            Quantity = 2,
                            TranDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 200000.0
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bán rượu trắng 35",
                            ProductId = 3,
                            Quantity = 150,
                            TranDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 6000000.0
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bán đòng đòng 35",
                            ProductId = 6,
                            Quantity = 35,
                            TranDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 2100000.0
                        },
                        new
                        {
                            Id = 13,
                            IngredientId = 3,
                            Name = "Mua nếp đen",
                            Quantity = 220,
                            TranDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 5060000.0
                        },
                        new
                        {
                            Id = 14,
                            IngredientId = 8,
                            Name = "Mua táo mèo",
                            Quantity = 10,
                            TranDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 300000.0
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bán rượu trắng 45",
                            ProductId = 1,
                            Quantity = 130,
                            TranDate = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 6500000.0
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bán rượu táo mèo",
                            ProductId = 8,
                            Quantity = 40,
                            TranDate = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 2400000.0
                        },
                        new
                        {
                            Id = 17,
                            IngredientId = 2,
                            Name = "Mua nếp cái hoa vàng",
                            Quantity = 160,
                            TranDate = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 4000000.0
                        },
                        new
                        {
                            Id = 18,
                            IngredientId = 5,
                            Name = "Mua men thuốc bắc",
                            Quantity = 2,
                            TranDate = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 300000.0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bán rượu trắng 40",
                            ProductId = 2,
                            Quantity = 140,
                            TranDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 6300000.0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bán bách nhật",
                            ProductId = 7,
                            Quantity = 45,
                            TranDate = new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 1800000.0
                        },
                        new
                        {
                            Id = 21,
                            IngredientId = 4,
                            Name = "Mua đòng đòng",
                            Quantity = 100,
                            TranDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 3000000.0
                        },
                        new
                        {
                            Id = 22,
                            IngredientId = 7,
                            Name = "Mua men lá",
                            Quantity = 3,
                            TranDate = new DateTime(2024, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 300000.0
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bán đòng đòng 45",
                            ProductId = 4,
                            Quantity = 50,
                            TranDate = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 3750000.0
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bán đòng đòng 40",
                            ProductId = 5,
                            Quantity = 60,
                            TranDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 4200000.0
                        },
                        new
                        {
                            Id = 25,
                            IngredientId = 3,
                            Name = "Mua nếp đen",
                            Quantity = 180,
                            TranDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 4140000.0
                        },
                        new
                        {
                            Id = 26,
                            IngredientId = 5,
                            Name = "Mua men thuốc bắc",
                            Quantity = 2,
                            TranDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 300000.0
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bán rượu trắng 45",
                            ProductId = 1,
                            Quantity = 110,
                            TranDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 5500000.0
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bán rượu táo mèo",
                            ProductId = 8,
                            Quantity = 50,
                            TranDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 3000000.0
                        },
                        new
                        {
                            Id = 29,
                            IngredientId = 2,
                            Name = "Mua nếp cái hoa vàng",
                            Quantity = 170,
                            TranDate = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 4250000.0
                        },
                        new
                        {
                            Id = 30,
                            IngredientId = 8,
                            Name = "Mua táo mèo",
                            Quantity = 15,
                            TranDate = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 450000.0
                        },
                        new
                        {
                            Id = 31,
                            Name = "Bán rượu trắng 40",
                            ProductId = 2,
                            Quantity = 130,
                            TranDate = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 5850000.0
                        },
                        new
                        {
                            Id = 32,
                            Name = "Bán bách nhật",
                            ProductId = 7,
                            Quantity = 40,
                            TranDate = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 1600000.0
                        },
                        new
                        {
                            Id = 33,
                            IngredientId = 1,
                            Name = "Mua gạo nếp",
                            Quantity = 200,
                            TranDate = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 4000000.0
                        },
                        new
                        {
                            Id = 34,
                            IngredientId = 7,
                            Name = "Mua men lá",
                            Quantity = 2,
                            TranDate = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 200000.0
                        },
                        new
                        {
                            Id = 35,
                            Name = "Bán rượu trắng 35",
                            ProductId = 3,
                            Quantity = 140,
                            TranDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 5600000.0
                        },
                        new
                        {
                            Id = 36,
                            Name = "Bán đòng đòng 35",
                            ProductId = 6,
                            Quantity = 45,
                            TranDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 2700000.0
                        },
                        new
                        {
                            Id = 37,
                            IngredientId = 4,
                            Name = "Mua đòng đòng",
                            Quantity = 80,
                            TranDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 2400000.0
                        },
                        new
                        {
                            Id = 38,
                            IngredientId = 5,
                            Name = "Mua men thuốc bắc",
                            Quantity = 3,
                            TranDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = false,
                            Value = 450000.0
                        },
                        new
                        {
                            Id = 39,
                            Name = "Bán đòng đòng 45",
                            ProductId = 4,
                            Quantity = 45,
                            TranDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 3375000.0
                        },
                        new
                        {
                            Id = 40,
                            Name = "Bán rượu trắng 45",
                            ProductId = 1,
                            Quantity = 120,
                            TranDate = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TranType = true,
                            Value = 6000000.0
                        });
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.BatchIngredient", b =>
                {
                    b.HasOne("RuKiSoBackEnd.Models.Domains.Batches", "Batch")
                        .WithMany("BatchIngredients")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuKiSoBackEnd.Models.Domains.Ingredients", "Ingredient")
                        .WithMany("BatchIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Batches", b =>
                {
                    b.HasOne("RuKiSoBackEnd.Models.Domains.Products", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Transactions", b =>
                {
                    b.HasOne("RuKiSoBackEnd.Models.Domains.Ingredients", "Ingredient")
                        .WithMany("Transactions")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RuKiSoBackEnd.Models.Domains.Products", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Batches", b =>
                {
                    b.Navigation("BatchIngredients");
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Ingredients", b =>
                {
                    b.Navigation("BatchIngredients");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RuKiSoBackEnd.Models.Domains.Products", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
