//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuKiSo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuKiSo.Resources.Text.AppTexts", typeof(AppTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nguyên liệu.
        /// </summary>
        internal static string AddIngredient {
            get {
                return ResourceManager.GetString("AddIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUKISO.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản xuất.
        /// </summary>
        internal static string Batches {
            get {
                return ResourceManager.GetString("Batches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nấu.
        /// </summary>
        internal static string Cook {
            get {
                return ResourceManager.GetString("Cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng quan.
        /// </summary>
        internal static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lợi nhuận ước tính.
        /// </summary>
        internal static string EstimatedProfit {
            get {
                return ResourceManager.GetString("EstimatedProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự kiến hoàn thành.
        /// </summary>
        internal static string EstimateEndDate {
            get {
                return ResourceManager.GetString("EstimateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang lên men.
        /// </summary>
        internal static string Fermenting {
            get {
                return ResourceManager.GetString("Fermenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên liệu.
        /// </summary>
        internal static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nguyên liệu.
        /// </summary>
        internal static string IngredientsList {
            get {
                return ResourceManager.GetString("IngredientsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên liệu chính.
        /// </summary>
        internal static string MainIngredients {
            get {
                return ResourceManager.GetString("MainIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lợi nhuận.
        /// </summary>
        internal static string MonthlyProfitChart {
            get {
                return ResourceManager.GetString("MonthlyProfitChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/yy.
        /// </summary>
        internal static string MonthYearStringFormat {
            get {
                return ResourceManager.GetString("MonthYearStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách mua nhiều nhất.
        /// </summary>
        internal static string MostPurchaseCustomers {
            get {
                return ResourceManager.GetString("MostPurchaseCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sản phẩm.
        /// </summary>
        internal static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản lượng dự kiến.
        /// </summary>
        internal static string ProjectedYield {
            get {
                return ResourceManager.GetString("ProjectedYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập.
        /// </summary>
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhập.
        /// </summary>
        internal static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán chạy nhất.
        /// </summary>
        internal static string TopSellerChart {
            get {
                return ResourceManager.GetString("TopSellerChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số nguyên liệu.
        /// </summary>
        internal static string TotalIngredient {
            get {
                return ResourceManager.GetString("TotalIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số sản phẩm.
        /// </summary>
        internal static string TotalProduct {
            get {
                return ResourceManager.GetString("TotalProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng giá trị.
        /// </summary>
        internal static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu nhập xuất tuần.
        /// </summary>
        internal static string WeeklyGoodsMovementChart {
            get {
                return ResourceManager.GetString("WeeklyGoodsMovementChart", resourceCulture);
            }
        }
    }
}
